# NOTE: contains intentional security test patterns for SAST/SCA/IaC scanning.
AWSTemplateFormatVersion: '2010-09-09'
Description: Sample CloudFormation template for an application

Resources:
  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sample-app-bucket-12345
      # FIX: Changed from PublicRead to Private to prevent public READ access (CWE-284)
      # This ensures the bucket ACL prohibits READ permission to everyone
      AccessControl: Private
      # FIX: Added BucketEncryption with AWS KMS to encrypt S3 bucket at rest
      # This ensures all objects in the bucket are encrypted with a customer-managed KMS key
      # Addresses AWS Inspector finding: S3 bucket must be encrypted with AWS KMS key
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !GetAtt S3KMSKey.Arn
            BucketKeyEnabled: true
      # Added cross-region replication configuration for improved data durability and availability
      ReplicationConfiguration:
        Role: !GetAtt ReplicationRole.Arn
        Rules:
          - Destination:
              Bucket: !Sub 'arn:aws:s3:::${AWS::StackName}-replica'
              # FIX: Removed 'Region' property - not allowed in ReplicationConfiguration Destination
              # The region is inferred from the bucket ARN specified above
            Status: Enabled
            Priority: 1
            DeleteMarkerReplication:
              Status: Enabled

  # FIX: Added KMS key for S3 bucket encryption
  # This customer-managed key provides centralized key management and encryption services
  S3KMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS key for S3 bucket encryption
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow S3 to use the key
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action:
              - 'kms:Decrypt'
              - 'kms:GenerateDataKey'
            Resource: '*'

  # FIX: Added KMS key alias for easier reference
  S3KMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/s3-bucket-encryption-key
      TargetKeyId: !Ref S3KMSKey

  # IAM role for S3 replication
  ReplicationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3ReplicationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetReplicationConfiguration
                  - s3:ListBucket
                Resource: !GetAtt AppBucket.Arn
              - Effect: Allow
                Action:
                  - s3:GetObjectVersionForReplication
                  - s3:GetObjectVersionAcl
                  - s3:GetObjectVersionTagging
                Resource: !Sub '${AppBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - s3:ReplicateObject
                  - s3:ReplicateDelete
                  - s3:ReplicateTags
                Resource: !Sub 'arn:aws:s3:::${AWS::StackName}-replica/*'

  AppRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AppRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AppFullPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'                       # Issue 2: wildcard action
                Resource: '*'                     # Issue 3: wildcard resource

  OpenSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: open-security-group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0                     # Issue 4: SSH open to the world
